In [5]:
!pip install sqlalchemy==1.3.9
!pip install ibm_db_sa

Requirement already satisfied: sqlalchemy==1.3.9 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (1.3.9)
Requirement already satisfied: ibm_db_sa in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (0.3.3)
Requirement already satisfied: sqlalchemy>=0.7.3 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from ibm_db_sa) (1.3.9)

In [3]:
%load_ext sql

In [6]:
# Enter the connection string for your Db2 on Cloud database instance below
# %sql ibm_db_sa://my-username:my-password@my-hostname:my-port/my-db-name?security=SSL
%sql ibm_db_sa://bwx77120:PuBVnax1FuMmgAdW@0c77d6f2-5da9-48a9-81f8-86b520b87518.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31198/bludb?security=SSL

'Connected: bwx77120@bludb'

In [4]:
%sql select * from SYSCAT.TABLES where TABNAME = 'SCHOOLS'

 * ibm_db_sa://bwx77120:***@0c77d6f2-5da9-48a9-81f8-86b520b87518.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31198/bludb
Done.

[('BWX77120', 'SCHOOLS', 'BWX77120', 'U', 'T', 'N', None, None, None, None, datetime.datetime(2021, 8, 18, 13, 43, 43, 968902), datetime.datetime(2021, 8, 18, 13, 43, 43, 968902), datetime.datetime(2021, 8, 18, 13, 43, 43, 968902), None, 78, 11, 4193, -1, -1, -1, -1, -1, -1, -1, -1, 'BWX77120SPACE1', None, None, 0, 0, 0, 0, 0, 0, 0, 'N', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', 1, ' ', '0', -1, 'N', ' ', None, 'R', ' ', 'N', '                                ', None, 'N', ' ', 'F', None, -1, 'N', 999, -1, -1.0, -1, -1.0, None, 1208, 'SYSIBM', 'IDENTITY', 'SYSIBM', 'IDENTITY', ' ', -1, datetime.datetime(2021, 8, 18, 13, 43, 43, 968902), 0, ' ', None, None, 'N', 'BWX77120', ' ', ' ', ' ', datetime.date(2021, 8, 18), ' ', 'N', 'R', 'N', -1.0, None)]

In [10]:
# number of columns in table schools
%sql select count(*) from SYSCAT.COLUMNS where TABNAME = 'SCHOOLS'

 * ibm_db_sa://bwx77120:***@0c77d6f2-5da9-48a9-81f8-86b520b87518.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31198/bludb
Done.

[(78,)]

In [11]:
# List all column names for schools
%sql select * from SYSCAT.COLUMNS WHERE TABNAME = 'SCHOOLS'

 * ibm_db_sa://bwx77120:***@0c77d6f2-5da9-48a9-81f8-86b520b87518.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31198/bludb
Done.

[('BWX77120', 'SCHOOLS', 'SCHOOL_ID', 0, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'NAME_OF_SCHOOL', 1, 'SYSIBM  ', 'VARCHAR', 64, 0, 'OCTETS', 64, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'Elementary, Middle, or High School', 2, 'SYSIBM  ', 'VARCHAR', 2, 0, 'OCTETS', 2, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'STREET_ADDRESS', 3, 'SYSIBM  ', 'VARCHAR', 29, 0, 'OCTETS', 29, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'CITY', 4, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'STATE', 5, 'SYSIBM  ', 'VARCHAR', 2, 0, 'OCTETS', 2, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'ZIP_CODE', 6, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'PHONE_NUMBER', 7, 'SYSIBM  ', 'VARCHAR', 14, 0, 'OCTETS', 14, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'LINK', 8, 'SYSIBM  ', 'VARCHAR', 78, 0, 'OCTETS', 78, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'NETWORK_MANAGER', 9, 'SYSIBM  ', 'VARCHAR', 40, 0, 'OCTETS', 40, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'COLLABORATIVE_NAME', 10, 'SYSIBM  ', 'VARCHAR', 34, 0, 'OCTETS', 34, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'ADEQUATE_YEARLY_PROGRESS_MADE_', 11, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'TRACK_SCHEDULE', 12, 'SYSIBM  ', 'VARCHAR', 12, 0, 'OCTETS', 12, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'CPS_PERFORMANCE_POLICY_STATUS', 13, 'SYSIBM  ', 'VARCHAR', 16, 0, 'OCTETS', 16, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'CPS_PERFORMANCE_POLICY_LEVEL', 14, 'SYSIBM  ', 'VARCHAR', 15, 0, 'OCTETS', 15, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'HEALTHY_SCHOOL_CERTIFIED', 15, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'SAFETY_ICON', 16, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'SAFETY_SCORE', 17, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'FAMILY_INVOLVEMENT_ICON', 18, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'FAMILY_INVOLVEMENT_SCORE', 19, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'ENVIRONMENT_ICON', 20, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'ENVIRONMENT_SCORE', 21, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'INSTRUCTION_ICON', 22, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'INSTRUCTION_SCORE', 23, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00', '\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'LEADERS_ICON', 24, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'LEADERS_SCORE', 25, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'TEACHERS_ICON', 26, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'TEACHERS_SCORE', 27, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'PARENT_ENGAGEMENT_ICON', 28, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'PARENT_ENGAGEMENT_SCORE', 29, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'PARENT_ENVIRONMENT_ICON', 30, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'PARENT_ENVIRONMENT_SCORE', 31, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'AVERAGE_STUDENT_ATTENDANCE', 32, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'RATE_OF_MISCONDUCTS__PER_100_STUDENTS_', 33, 'SYSIBM  ', 'DECIMAL', 5, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', -1, '\x00\x00\x00', '\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'AVERAGE_TEACHER_ATTENDANCE', 34, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'INDIVIDUALIZED_EDUCATION_PROGRAM_COMPLIANCE_RATE', 35, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00\x00\x00\x00', '\x00\x00\x00\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'PK_2_LITERACY__', 36, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'PK_2_MATH__', 37, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'GR3_5_GRADE_LEVEL_MATH__', 38, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'GR3_5_GRADE_LEVEL_READ__', 39, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'GR3_5_KEEP_PACE_READ__', 40, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'GR3_5_KEEP_PACE_MATH__', 41, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'GR6_8_GRADE_LEVEL_MATH__', 42, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'GR6_8_GRADE_LEVEL_READ__', 43, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'GR6_8_KEEP_PACE_MATH_', 44, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'GR6_8_KEEP_PACE_READ__', 45, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('BWX77120', 'SCHOOLS', 'GR_8_EXPLORE_MATH__', 46, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', -1, '\x00\x00\x00\x00', '\x00\x00\x00\x00', -1, None, 0, -1, -1, -1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),

In [15]:
# List all schools that are elementary
%sql select COUNT(*) from schools where "Elementary, Middle, or High School" ='ES'

 * ibm_db_sa://bwx77120:***@0c77d6f2-5da9-48a9-81f8-86b520b87518.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31198/bludb
Done.

[(462,)]

In [18]:
# schools' maximun safety score
%sql SELECT MAX(SAFETY_SCORE) FROM SCHOOLS

 * ibm_db_sa://bwx77120:***@0c77d6f2-5da9-48a9-81f8-86b520b87518.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31198/bludb
Done.

[(99,)]

In [21]:
%sql select school_id, name_of_school, safety_score from schools where safety_score = 99

 * ibm_db_sa://bwx77120:***@0c77d6f2-5da9-48a9-81f8-86b520b87518.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31198/bludb
Done.

[(610038, 'Abraham Lincoln Elementary School', 99),
 (609799, 'Alexander Graham Bell Elementary School', 99),
 (610084, 'Annie Keller Elementary Gifted Magnet School', 99),
 (609820, 'Augustus H Burley Elementary School', 99),
 (610132, 'Edgar Allan Poe Elementary Classical School', 99),
 (609901, 'Edgebrook Elementary School', 99),
 (610073, 'Ellen Mitchell Elementary School', 99),
 (610066, 'James E McDade Elementary Classical School', 99),
 (609803, 'James G Blaine Elementary School', 99),
 (610033, 'LaSalle Elementary Language Academy', 99),
 (610355, 'Mary E Courtenay Elementary Language Arts Center', 99),
 (609749, 'Northside College Preparatory High School', 99),
 (609744, 'Northside Learning Center High School', 99),
 (610099, 'Norwood Park Elementary School', 99),
 (610105, 'Oriole Park Elementary School', 99),
 (610155, 'Sauganash Elementary School', 99),
 (609880, 'Stephen Decatur Classical Elementary School', 99),
 (610249, 'Talman Elementary School', 99),
 (610230, 'Wildwood Elementary School', 99)]

In [34]:
#What are the top 10 schools with the highest "Average Student Attendance"?
%sql select school_id, name_of_school,AVERAGE_STUDENT_ATTENDANCE FROM schools order by AVERAGE_STUDENT_ATTENDANCE desc nulls last limit 10

 * ibm_db_sa://bwx77120:***@0c77d6f2-5da9-48a9-81f8-86b520b87518.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31198/bludb
Done.

[(609959, 'John Charles Haines Elementary School', '98.40%'),
 (610217, 'James Ward Elementary School', '97.80%'),
 (610132, 'Edgar Allan Poe Elementary Classical School', '97.60%'),
 (610329, 'Orozco Fine Arts & Sciences Elementary School', '97.60%'),
 (609842, 'Rachel Carson Elementary School', '97.60%'),
 (610084, 'Annie Keller Elementary Gifted Magnet School', '97.50%'),
 (610060, 'Andrew Jackson Elementary Language Academy', '97.40%'),
 (610298, 'Lenart Elementary Regional Gifted Center', '97.40%'),
 (610515, 'Disney II Magnet School', '97.30%'),
 (610207, 'John H Vanderpoel Elementary Magnet School', '97.20%')]

In [38]:
#Retrieve the list of 5 Schools with the lowest Average Student Attendance sorted in ascending order based on attendance
%sql select school_id, name_of_school,AVERAGE_STUDENT_ATTENDANCE FROM schools order by AVERAGE_STUDENT_ATTENDANCE asc limit 5

 * ibm_db_sa://bwx77120:***@0c77d6f2-5da9-48a9-81f8-86b520b87518.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31198/bludb
Done.

[(609702, 'Richard T Crane Technical Preparatory High School', '57.90%'),
 (609871, 'Barbara Vick Early Childhood & Family Center', '60.90%'),
 (609736, 'Dyett High School', '62.50%'),
 (609727, 'Wendell Phillips Academy High School', '63.00%'),
 (610389, 'Orr Academy High School', '66.30%')]

In [46]:
#Which Schools have Average Student Attendance lower than 70%?
%sql select school_id,name_of_school,AVERAGE_STUDENT_ATTENDANCE FROM schools where CAST(REPLACE(Average_Student_Attendance, '%', '') AS DOUBLE ) < 70\
order by AVERAGE_STUDENT_ATTENDANCE

 * ibm_db_sa://bwx77120:***@0c77d6f2-5da9-48a9-81f8-86b520b87518.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31198/bludb
Done.

[(609702, 'Richard T Crane Technical Preparatory High School', '57.90%'),
 (609871, 'Barbara Vick Early Childhood & Family Center', '60.90%'),
 (609736, 'Dyett High School', '62.50%'),
 (609727, 'Wendell Phillips Academy High School', '63.00%'),
 (610389, 'Orr Academy High School', '66.30%'),
 (609722, 'Manley Career Academy High School', '66.80%'),
 (609674, 'Chicago Vocational Career Academy High School', '68.80%'),
 (609759, 'Roberto Clemente Community Academy High School', '69.60%')]

In [51]:
#Get the total College Enrollment for each Community Area
%sql select SUM(COLLEGE_ENROLLMENT) AS Total_Enrollment,COMMUNITY_AREA_NAME\
FROM SCHOOLS group by COMMUNITY_AREA_NAME

 * ibm_db_sa://bwx77120:***@0c77d6f2-5da9-48a9-81f8-86b520b87518.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31198/bludb
Done.

[(6864, 'ALBANY PARK'),
 (4823, 'ARCHER HEIGHTS'),
 (1458, 'ARMOUR SQUARE'),
 (6483, 'ASHBURN'),
 (4175, 'AUBURN GRESHAM'),
 (10933, 'AUSTIN'),
 (1522, 'AVALON PARK'),
 (3640, 'AVONDALE'),
 (14386, 'BELMONT CRAGIN'),
 (1636, 'BEVERLY'),
 (3167, 'BRIDGEPORT'),
 (9647, 'BRIGHTON PARK'),
 (549, 'BURNSIDE'),
 (1568, 'CALUMET HEIGHTS'),
 (5042, 'CHATHAM'),
 (7086, 'CHICAGO LAWN'),
 (2085, 'CLEARING'),
 (4670, 'DOUGLAS'),
 (4568, 'DUNNING'),
 (5337, 'EAST GARFIELD PARK'),
 (5305, 'EAST SIDE'),
 (4600, 'EDGEWATER'),
 (910, 'EDISON PARK'),
 (6832, 'ENGLEWOOD'),
 (1431, 'FOREST GLEN'),
 (531, 'FULLER PARK'),
 (9915, 'GAGE PARK'),
 (4552, 'GARFIELD RIDGE'),
 (2809, 'GRAND BOULEVARD'),
 (4051, 'GREATER GRAND CROSSING'),
 (963, 'HEGEWISCH'),
 (3975, 'HERMOSA'),
 (8620, 'HUMBOLDT PARK'),
 (1930, 'HYDE PARK'),
 (7764, 'IRVING PARK'),
 (1755, 'JEFFERSON PARK'),
 (4287, 'KENWOOD'),
 (7055, 'LAKE VIEW'),
 (5615, 'LINCOLN PARK'),
 (4132, 'LINCOLN SQUARE'),
 (7351, 'LOGAN SQUARE'),
 (871, 'LOOP'),
 (7257, 'LOWER WEST SIDE'),
 (1552, 'MCKINLEY PARK'),
 (1317, 'MONTCLARE'),
 (3271, 'MORGAN PARK'),
 (2091, 'MOUNT GREENWOOD'),
 (3362, 'NEAR NORTH SIDE'),
 (1378, 'NEAR SOUTH SIDE'),
 (7975, 'NEAR WEST SIDE'),
 (7922, 'NEW CITY'),
 (7541, 'NORTH CENTER'),
 (5146, 'NORTH LAWNDALE'),
 (4210, 'NORTH PARK'),
 (6469, 'NORWOOD PARK'),
 (140, 'OAKLAND'),
 (786, 'OHARE'),
 (6954, 'PORTAGE PARK'),
 (1620, 'PULLMAN'),
 (1547, 'RIVERDALE'),
 (4068, 'ROGERS PARK'),
 (7020, 'ROSELAND'),
 (4043, 'SOUTH CHICAGO'),
 (1859, 'SOUTH DEERING'),
 (14793, 'SOUTH LAWNDALE'),
 (4543, 'SOUTH SHORE'),
 (4388, 'UPTOWN'),
 (4006, 'WASHINGTON HEIGHTS'),
 (2648, 'WASHINGTON PARK'),
 (3700, 'WEST ELSDON'),
 (5946, 'WEST ENGLEWOOD'),
 (2622, 'WEST GARFIELD PARK'),
 (4207, 'WEST LAWN'),
 (3240, 'WEST PULLMAN'),
 (8197, 'WEST RIDGE'),
 (9429, 'WEST TOWN'),
 (4206, 'WOODLAWN')]

In [59]:
#Get the 5 Community Areas with the least total College Enrollment sorted in ascending order
%sql select school_id,name_of_school,COLLEGE_ENROLLMENT,COMMUNITY_AREA_NAME FROM schools where CAST(REPLACE(Average_Student_Attendance, '%', '') AS DOUBLE ) < 70\
order by COLLEGE_ENROLLMENT limit 5

 * ibm_db_sa://bwx77120:***@0c77d6f2-5da9-48a9-81f8-86b520b87518.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31198/bludb
Done.

[(609871, 'Barbara Vick Early Childhood & Family Center', 204, 'MORGAN PARK'),
 (609736, 'Dyett High School', 318, 'WASHINGTON PARK'),
 (609702, 'Richard T Crane Technical Preparatory High School', 478, 'NEAR WEST SIDE'),
 (609727, 'Wendell Phillips Academy High School', 590, 'DOUGLAS'),
 (609722, 'Manley Career Academy High School', 599, 'EAST GARFIELD PARK')]

In [63]:
#List 5 schools with lowest safety score.
%sql select NAME_OF_SCHOOL,SAFETY_SCORE FROM SCHOOLS ORDER BY SAFETY_SCORE NULLS LAST LIMIT 5

 * ibm_db_sa://bwx77120:***@0c77d6f2-5da9-48a9-81f8-86b520b87518.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31198/bludb
Done.

[('Edmond Burke Elementary School', 1),
 ("Luke O'Toole Elementary School", 5),
 ('George W Tilton Elementary School', 6),
 ('Foster Park Elementary School', 11),
 ('Emil G Hirsch Metropolitan High School', 13)]